config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index]
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:edit, :update, :new, :create]
  end

  resources :posts, only: [ :show, ]
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :sub_id, :user_id, :title, presence: true
  

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  belongs_to(
    :sub,
    class_name: "Sub",
    foreign_key: :sub_id,
    primary_key: :id
  )
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :user_id, presence: true
  validates :title, uniqueness: true

  belongs_to(
    :mod,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :sub_id,
    primary_key: :id
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, presence: true
  validates :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many(
    :subs,
    class_name: "Sub",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  after_initialize :ensure_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  attr_reader :password

  def ensure_token
    self.session_token ||= User.generate_session_token
  end

  def reset_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :auth_token

  def auth_token
    x = <<-HTML
      <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
    HTML
    x.html_safe
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_token
  end

  def logged_in?
    !!current_user
  end

  def logout!
    session[:session_token] = nil
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @post.sub_id = params[:sub_id]
  end

  def create
    @post = Post.new(post_params)
    @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.sub_id = params[:sub_id]
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:user_id,
                                   :content,
                                   :sub_id,
                                   :title,
                                   :url_attrib)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(*user_params.values)
    if user
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end

  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :user_is_logged_in?, only: [ :new, :create, :edit, :update]
  before_action :user_is_mod?, only: [ :edit, :update ]
  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end

  private
    def sub_params
        params.require(:sub).permit(:user_id, :title, :description)
    end

    def user_is_mod?
      new_sub = Sub.find(params[:id])
      redirect_to user_url(current_user) unless new_sub.mod == current_user
    end

    def user_is_logged_in?
      redirect_to new_session_url unless logged_in?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :edit
    end

    def destroy
      User.find(params[:id]).destroy
      redirect_to :new
    end
  end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redditclone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul>
  <% if flash.now[:errors] %>
    <% flash.now[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  <% end %>
  </ul>
<%= render 'shared/header' %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% if post.persisted? %>
<form action="<%= sub_post_url(post) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
<% else %>
<form action="<%= sub_posts_url(post.sub) %>" method="post">
<% end %>
  <%= auth_token %>
  <label>Title</label>
  <input type="text" name="post[title]" value="<%= post.title %>">
  <br>
  <label>Content</label>
  <textarea name="post[content]" rows="8"
      cols="40" value="<%= post.content %>"></textarea>
  <br>
  <label>Link</label>
  <input type="text" name="post[url_attrib]" value="<%= post.url_attrib %>">
  <br>
  <input type="hidden" name="post[user_id]" value="<%= current_user.id %>">
  <br>

  <br>
  <button>Submit</button>
</form>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<% if post.persisted? %>
<form action="<%= post_url(post) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
<% else %>
<form action="<%= posts_url %>" method="post">
<% end %>
  <%= auth_token %>
  <label>Title</label>
  <input type="text" name="post[title]" value="<%= post.title %>">
  <br>
  <label>Content</label>
  <textarea name="post[content]" rows="8"
      cols="40" value="<%= post.description"></textarea>
  <br>
  <label>Link</label>
  <input type="text" name="post[url_attrib]" value="<%= post.url_attrib %>">
  <br>
  <input type="hidden" name="post[user_id]" value="<%= current_user.id %>">
</form>

app/views/shared/_header.html.haml
-if logged_in?
  %form{:action => session_url(session), :method => "post"}
    =auth_token
    %input{:type => "hidden", :name => "_method", :value => "delete"}
    %button logout
  %a{href: user_url(current_user) }
    My profile
  %a{href: new_sub_url}
    create new sub
-else
  %a{:href => new_session_url}
    log in

%a{ href: subs_url }
  view all subs


  -# -All subs: link to Subs controller index action
  -#
  -# -Create subs: logged in users can do dis.

app/views/subs/_form.html.erb
<%if new_sub.persisted? %>
  <form action="<%= sub_url(new_sub) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
<% else %>
  <form action="subs_url" method="POST">
<% end %>
  <%= auth_token %>
  <label>Title</label>
  <input type="text" name="sub[title]" value="<%=new_sub.title %>">
  <br>
  <label>Description</label>
  <textarea name="sub[description]" value="<%= new_sub.description %>"></textarea>
  <br>
  <input type="hidden" name="sub[user_id]" value="<%= current_user.id %>">
  <button>Submit</button>
</form>

app/views/subs/edit.html.haml
%h1 Edit the sub: #{@sub.title}

=render 'form', new_sub: @sub

app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
  <% @subs.each do |sub|%>
    <li> <a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>

app/views/subs/new.html.haml
%h1 Create a new Sub

=render "form", new_sub: @sub

app/views/subs/show.html.haml
%h1
  = @sub.title

%p
  = @sub.description
%ul
  mod:
  %a{href: user_url(@sub.mod)}
    = @sub.mod.username

- if logged_in?
  %a{href: new_sub_post_url(@sub)}
    create post
  - if current_user == @sub.mod
    %a{href: edit_sub_url(@sub)}
      edit sub

- @posts.each do |post|
  %a{href: post_url(post)}
    = post.title

app/views/users/_form.html.haml
%h1= @user.id ? "Edit" : "Signup"

%form{:action => users_url, :method => "post"}
  = auth_token
  %label Username
  %input{type: "text", name: "user[username]", value: user.username}
  <br>
  %label Password
  %input{type: "password", name: "user[password]"}
  <br>
  %button Submit

app/views/users/edit.html.haml
= render "form", user: @user
%a{ :href => user_url(@user)}
  back to user

app/views/users/new.html.haml
= render "form", user: @user 

app/views/users/show.html.haml
%h1= "Hello #{@user.username}"
%a{href: edit_user_url(@user)}
  Edit